Bookstore/Areas/Admin/Controllers/AdminBooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bookstore.Entity;
using AspNetCoreHero.ToastNotification.Abstractions;
using AspNetCoreHero.ToastNotification.Notyf;
using PagedList.Core;
using Bookstore.Helpper;

namespace Bookstore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminBooksController : Controller
    {
        private readonly dbBookstoreContext _context;
        public INotyfService _notyfService { get; }

        public AdminBooksController(dbBookstoreContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        public IActionResult BookIndex(int page = 1, int TypeID = 0)
        {
            var pageNumber = page;
            var pageSize = 8;

            List<TbBook> lsBooks = new List<TbBook>();

            if (TypeID != 0)
            {
                lsBooks = _context.TbBooks
                    .AsNoTracking()
                    .Where(x => x.TypeId == TypeID)
                    .Include(x => x.Type)
                    .OrderByDescending(x => x.BookId).ToList();
            }
            else
            {
                lsBooks = _context.TbBooks
                    .AsNoTracking()
                    .Include(x => x.Type)
                    .OrderByDescending(x => x.BookId).ToList();
            }

            PagedList<TbBook> models = new PagedList<TbBook>(lsBooks.AsQueryable(), pageNumber, pageSize);
            ViewBag.CurrentTypeID = TypeID;
            ViewBag.CurrentPage = pageNumber;
            ViewData["NXB"] = new SelectList(_context.TbPublishers, "PublisherId", "PublisherName");
            ViewData["TheLoai"] = new SelectList(_context.TbBookTypes, "TypeId", "TypeName", TypeID);
            return View(models);
        }

        public IActionResult Filtter(int TypeID = 0)
        {
            var url = $"/Admin/AdminBooks/BookIndex?TypeID={TypeID}";
            if (TypeID == 0)
            {
                url = $"/Admin/AdminBooks/BookIndex";
            }

            return Json(new { status = "success", redirectUrl = url });
        }

        public async Task<IActionResult> BookDetails(int? id)
        {
            if (id == null || _context.TbBooks == null)
            {
                return NotFound();
            }

            var tbBook = await _context.TbBooks
                .Include(t => t.Publisher)
                .Include(t => t.Type)
                .FirstOrDefaultAsync(m => m.BookId == id);
            if (tbBook == null)
            {
                return NotFound();
            }

            return View(tbBook);
        }

        public IActionResult BookCreate()
        {
            ViewData["NXB"] = new SelectList(_context.TbPublishers, "PublisherId", "PublisherName");
            ViewData["TheLoai"] = new SelectList(_context.TbBookTypes, "TypeId", "TypeName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BookCreate([Bind("BookId,BookName,Author,Desription,Status,IsHot,Image,ListImage,Quantity,Price,PromotionPrice,Language,Translator,Page,PublishYear,TypeId,PublisherId")] TbBook Book, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                Book.BookName = Utilities.ToTitleCase(Book.BookName);
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string image = Utilities.SEOUrl(Book.BookName) + extension;
                    Book.Image = await Utilities.UploadFile(fThumb, @"books", image.ToLower());
                }
                if (string.IsNullOrEmpty(Book.Image)) Book.Image = "default-book.jpg";

                _context.Add(Book);
                await _context.SaveChangesAsync();
                _notyfService.Success("Thêm sách thành công");
                return RedirectToAction(nameof(BookIndex));
            }
            ViewData["NXB"] = new SelectList(_context.TbPublishers, "PublisherId", "PublisherName", Book.PublisherId);
            ViewData["TheLoai"] = new SelectList(_context.TbBookTypes, "TypeId", "TypeName", Book.TypeId);
            return View(Book);
        }

        public async Task<IActionResult> BookEdit(int? id)
        {
            if (id == null || _context.TbBooks == null)
            {
                return NotFound();
            }

            var Book = await _context.TbBooks.FindAsync(id);
            if (Book == null)
            {
                return NotFound();
            }
            ViewData["NXB"] = new SelectList(_context.TbPublishers, "PublisherId", "PublisherName");
            ViewData["TheLoai"] = new SelectList(_context.TbBookTypes, "TypeId", "TypeName");
            return View(Book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BookEdit(int id, [Bind("BookId,BookName,Author,Desription,Status,IsHot,Image,ListImage,Quantity,Price,PromotionPrice,Language,Translator,Page,PublishYear,TypeId,PublisherId")] TbBook Book, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != Book.BookId)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            //{
                try
                {
                    Book.BookName = Utilities.ToTitleCase(Book.BookName);
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string image = Utilities.SEOUrl(Book.BookName) + extension;
                        Book.Image = await Utilities.UploadFile(fThumb, @"books", image.ToLower());
                    }
                    //if (string.IsNullOrEmpty(Book.Image)) Book.Image = Book.Image;
                    _context.Update(Book);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Cập nhật sách thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbBookExists(Book.BookId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(BookIndex));
            //}
            //ViewData["NXB"] = new SelectList(_context.TbPublishers, "PublisherId", "PublisherName", Book.PublisherId);
            //ViewData["TheLoai"] = new SelectList(_context.TbBookTypes, "TypeId", "TypeName", Book.TypeId);
            //return View(Book);
        }

        private bool TbBookExists(int id)
        {
          return (_context.TbBooks?.Any(e => e.BookId == id)).GetValueOrDefault();
        }
    }
}

Bookstore/Areas/Admin/Controllers/AdminHomeController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Bookstore.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bookstore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminHomeController : Controller
    {
        private readonly dbBookstoreContext _context;
        public INotyfService _notyfService { get; }

        public AdminHomeController(dbBookstoreContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        [Route("/Admin")]
        public IActionResult Admin()
        {
            int gia1 = 0;

            DateTime StartDate = DateTime.Today.AddDays(-30);
            DateTime EndDate1 = DateTime.Now;

            var hoadonban = _context.TbOrders.Where(s => s.OrderDate >= StartDate && s.OrderDate <= EndDate1).ToList();
            foreach (var element in hoadonban)
            {
                var dondat = _context.TbOrderDetails.Where(s => s.OrderId == element.OrderId).ToList();
                foreach (var element2 in dondat)
                {
                    if (element2.PromotionPrice == null)
                    {
                        int strSanPham = (int)(Convert.ToInt32(element2.Price) * element2.Amount);
                        gia1 += strSanPham;
                    }
                    else
                    {
                        int strSanPham = (int)(Convert.ToInt32(element2.PromotionPrice) * element2.Amount);
                        gia1 += strSanPham;
                    }
                }
            }
            ViewBag.gialai = gia1;

            ViewBag.CountBook = _context.TbBooks.ToList().Count();
            ViewBag.CountOrder = _context.TbOrders.ToList().Count();
            ViewBag.CountCustomer = _context.TbCustomers.ToList().Count();


            ViewBag.loai1 = _context.TbBooks.Where(s => s.TypeId == 1).Count();
            ViewBag.loai2 = _context.TbBooks.Where(s => s.TypeId == 3).Count();
            ViewBag.loai3 = _context.TbBooks.Where(s => s.TypeId == 4).Count();
            ViewBag.loai4 = _context.TbBooks.Where(s => s.TypeId == 5).Count();
            ViewBag.loai5 = _context.TbBooks.Where(s => s.TypeId == 6).Count();
            ViewBag.loai6 = _context.TbBooks.Where(s => s.TypeId == 7).Count();
            ViewBag.loai7 = _context.TbBooks.Where(s => s.TypeId == 1008).Count();
            ViewBag.loai8 = _context.TbBooks.Where(s => s.TypeId == 1009).Count();
            ViewBag.loai9 = _context.TbBooks.Where(s => s.TypeId == 1010).Count();

            return View();
        }
    }
}

Bookstore/Areas/Admin/Views/AdminBooks/BookCreate.cshtml
@model Bookstore.Entity.TbBook

@{
    ViewData["Title"] = "Thêm sách";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-controller="AdminBooks" asp-action="BookCreate" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-right justify-content-between">
            <div class="media align-items-center m-b-15">
                
            </div>
            <div class="m-b-15">
                <button type="submit" class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Lưu</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin sách</a>
            </li>
            @*<li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Option Info</a>
            </li>*@
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Mô tả</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold">Tên sách</label>
                        <input type="text" class="form-control" asp-for="BookName">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold">Tác giả</label>
                        <input type="text" class="form-control" asp-for="Author">
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="productCategory">Thể loại</label>
                            <select class="custom-select" asp-for="TypeId" asp-items="ViewBag.TheLoai">
                                <option value="" disabled selected>Chọn thể loại</option>
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="productCategory">Nhà xuất bản</label>
                            <select class="custom-select" asp-for="PublisherId" asp-items="ViewBag.NXB">
                                <option value="" disabled selected>Chọn nhà xuất bản</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-3">
                            <label class="font-weight-semibold">Ngôn ngữ</label>
                            <input type="text" class="form-control" asp-for="Language">
                        </div>
                        <div class="form-group col-md-3">
                            <label class="font-weight-semibold">Người dịch</label>
                            <input type="text" class="form-control" asp-for="Translator">
                        </div>
                        <div class="form-group col-md-3">
                            <label class="font-weight-semibold">Năm phát hành</label>
                            <input type="text" class="form-control" asp-for="PublishYear">
                        </div>
                        <div class="form-group col-md-3">
                            <label class="font-weight-semibold">Số trang</label>
                            <input type="text" class="form-control" asp-for="Page">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-4">
                            <label class="font-weight-semibold">Giá</label>
                            <input type="text" class="form-control" asp-for="Price">
                        </div>
                        <div class="form-group col-md-4">
                            <label class="font-weight-semibold">Giá khuyến mãi</label>
                            <input type="text" class="form-control" asp-for="PromotionPrice">
                        </div>
                        <div class="form-group col-md-4">
                            <label class="font-weight-semibold">Số lượng</label>
                            <input type="text" class="form-control" asp-for="Quantity">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Ảnh chính</label>
                        <input multiple id="fileUpload" asp-for="Image" name="fthumb" type="file" class="form-control-file hidden" />
                        <span asp-validation-for="Image" class="text-danger"></span>
                    </div>
                    <div class="form-group d-flex align-items-center">
                        <div class="switch m-r-10">
                            <input asp-for="Status" type="checkbox" id="switch-1" checked="">
                            <label for="switch-1"></label>
                        </div>
                        <label>Đang bán</label>
                    </div>
                    <div class="form-group d-flex align-items-center">
                        <div class="switch m-r-10">
                            <input asp-for="IsHot" type="checkbox" id="switch-2">
                            <label for="switch-2"></label>
                        </div>
                        <label>Sản phẩm hot</label>
                    </div>

                </div>
            </div>
        </div>
        @*<div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productSize">Size</label>
                        <select class="select2" id="productSize" multiple="multiple">
                            <option value="40" selected>40</option>
                            <option value="42" selected>42</option>
                            <option value="44">44</option>
                            <option value="46">46</option>
                            <option value="48">48</option>
                            <option value="50">50</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">Colors</label>
                        <select class="select2" id="productColors" multiple="multiple">
                            <option value="db" selected>Dark Blue</option>
                            <option value="g" selected>Gray</option>
                            <option value="gb" selected>Gray Blue</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">Fit</label>
                        <select class="custom-select" id="productFit">
                            <option value="skinny" selected>Skinny</option>
                            <option value="slim">Slim</option>
                            <option value="regular">Regular</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productMaterial">Material</label>
                        <select class="select2" id="productMaterial" multiple="multiple">
                            <option value="polyester" selected>Polyester</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productShip">Ship From</label>
                        <select class="custom-select" id="productShip">
                            <option value="columbia" selected>Columbia</option>
                            <option value="brazil">Brazil</option>
                            <option value="chile">Chile</option>
                            <option value="argentina">Argentina</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>*@
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <div id="productDescription">
                        <p>Special cloth alert. The key to more success is to have a lot of pillows. Surround yourself with angels, positive energy, beautiful people, beautiful souls, clean heart, angel. They will try to close the door on you, just open it. A major key, never panic. Don’t panic, when it gets crazy and rough, don’t panic, stay calm. They key is to have every key, the key to open every door.The other day the grass was brown, now it’s green because I ain’t give up. Never surrender. Lion! I’m up to something. Always remember in the jungle there’s a lot of they in there, after you overcome they, you will make it to paradise.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <script src="~/Admin/assets/vendors/select2/select2.min.js"></script>
    <script src="~/Admin/assets/vendors/quill/quill.min.js"></script>
    <script src="~/Admin/assets/js/pages/e-commerce-product-edit.js"></script>
}

Bookstore/Areas/Admin/Views/AdminBooks/BookDelete.cshtml
@model Bookstore.Entity.TbBook

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TbBook</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Desription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Desription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsHot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsHot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ListImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ListImage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PromotionPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PromotionPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publisher.PublisherId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type.TypeId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BookId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Bookstore/Areas/Admin/Views/AdminBooks/BookIndex.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<Bookstore.Entity.TbBook>

@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Quản lý sách" + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    var number = 1;
}

<div id="modal" class="modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button id="Close" type="button" class="close btn btn-danger btn-tone m-r-5" data-dismiss="modal">
                    <i class="anticon anticon-close"></i>
                </button>
            </div>
            <div class="modal-body" id="sub-modal">
            </div>
        </div>
    </div>
</div>

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="AdminHome" asp-action="Admin"> <i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
            <div class="input-group rounded" style="width:300px">
                <input id="keyword" name="keyword" type="search" class="form-control rounded" placeholder="Tìm kiếm sản phẩm" aria-label="Search" aria-describedby="search-addon" />
                <span class="input-group-text border-0" id="search-addon">
                    <i class='bx bx-search'></i>
                </span>
            </div>
            <hr />
        <div class="row m-b-30">
            <div class="col-lg-8">
                <div class="d-md-flex">
                    <div class="m-b-10 m-r-15">
                        <select id="txtTypeID" class="custom-select" style="min-width: 180px;" asp-items="ViewBag.TheLoai">
                            <option value="" disabled selected>Chọn thể loại</option>
                            <option value="0">Tất cả</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 text-right">
                <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminBooks" asp-action="BookCreate">
                    <i class="anticon anticon-plus-circle m-r-5"></i>
                    <span>Thêm sách</span>
                </a>
            </div>
        </div>

        <div class="table-responsive">
            <table style="text-align:center" class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Thông tin</th>
                        <th>Giá</th>
                        <th>Khuyến mãi</th>
                        <th>Ảnh</th>
                        <th>Trạng thái</th>
                        <th>Cập nhật</th>
                    </tr>
                </thead>
                <tbody style="text-align:left" id="records_table">
                    @if (Model != null)
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @number
                                    @{
                                        number++;
                                    }
                                </td>
                                <td>
                                    <p class="font-weight-bold">Tên: @item.BookName</p>
                                    <p class="font-weight-bold">Thể loại: @item.Type.TypeName</p>
                                </td>
                                <td>
                                    @if (item.Price != null)
                                    {
                                        <p>@item.Price.Value.ToString("#,##0") VNĐ</p>
                                    }
                                    else
                                    {
                                        <p>@item.Price VNĐ</p>
                                    }
                                </td>
                                <td>
                                    @if (item.PromotionPrice != null)
                                    {
                                        <p>@item.PromotionPrice.Value.ToString("#,##0") VNĐ</p>
                                    }
                                    else
                                    {
                                        <p>@item.PromotionPrice</p>
                                    }
                                </td>
                                <td>
                                    <img width="120px" src="~/images/books/@item.Image" alt="@item.Image" />
                                </td>
                                <td>
                                    @if (item.Status == true)
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge rounded-pill bg-success">Đang bán</div>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge rounded-pill bg-danger">Dừng bán</div>
                                        </div>
                                    }
                                </td>
                                <td class="text-right">
                                    <a asp-controller="AdminBooks" asp-action="BookDetails" asp-route-id="@item.BookId" class="btn btn-outline-primary"><i class='bx bx-detail'></i></a>
                                    <a asp-controller="AdminBooks" asp-action="BookEdit" asp-route-id="@item.BookId" class="btn btn-outline-warning"><i class='bx bx-edit-alt'></i></a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="pagination" list="@Model" options="@PagedListRenderOptions.Bootstrap4PageNumbersPlusFirstAndLast" asp-route-TypeID="@ViewBag.CurrentTypeID" asp-area="Admin" asp-controller="AdminBooks" asp-action="BookIndex" />
                </ul>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script>
        $(document).ready(function () {
            jQuery("#txtTypeID").change(function () {
                var typeID = jQuery(this).children(":selected").attr("value");
                typeID = parseFloat(typeID);
                $('#txtTypeID option').removeAttr('selected');
                $("#txtTypeID > [value =" + typeID + "]").attr("selected", "true");
                $.ajax({
                    url: '/Admin/AdminBooks/Filtter',
                    dataType: "json",
                    type: "GET",
                    data: {
                        TypeID: typeID
                    },
                    async: true,
                    success: function (results) {
                        if (results.status == "success") {
                            window.location.href = results.redirectUrl;
                        }
                    },
                    error: function (xhr) {
                        alert('error');
                    }
                });
            });

            $("#keyword").keyup(function () {
                var strkeyword = $('#keyword').val();
                $.ajax({
                    url: '/Admin/Search/FindProduct/',
                    datatype: "json",
                    type: "POST",
                    data: { keyword: strkeyword },
                    async: true,
                    success: function (results) {
                        $("#records_table").html("");
                        $("#records_table").html(results);
                    },
                    error: function (xhr) {
                        alert('error');
                    }
                });
            });

        });
    </script>
}