Bookstore/Areas/Admin/Controllers/AdminPublisherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bookstore.Entity;
using AspNetCoreHero.ToastNotification.Abstractions;
using PagedList.Core;

namespace Bookstore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminPublisherController : Controller
    {
        private readonly dbBookstoreContext _context;
        public INotyfService _notyfService { get; }

        public AdminPublisherController(dbBookstoreContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        public IActionResult PublisherIndex(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 5;
            var lsPublisher = _context.TbPublishers.AsNoTracking().OrderByDescending(x => x.PublisherName);

            PagedList<TbPublisher> models = new PagedList<TbPublisher>(lsPublisher, pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        public IActionResult PublisherCreate()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PublisherCreate([Bind("PublisherId,PublisherName,Status")] TbPublisher tbPublisher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tbPublisher);
                await _context.SaveChangesAsync();
                _notyfService.Success("Đã thêm nhà xuất bản");
                return RedirectToAction(nameof(PublisherIndex));
            }
            return View(tbPublisher);
        }

        public async Task<IActionResult> PublisherEdit(int? id)
        {
            if (id == null || _context.TbPublishers == null)
            {
                return NotFound();
            }

            var tbPublisher = await _context.TbPublishers.FindAsync(id);
            if (tbPublisher == null)
            {
                return NotFound();
            }
            return View(tbPublisher);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PublisherEdit(int id, [Bind("PublisherId,PublisherName,Status")] TbPublisher tbPublisher)
        {
            if (id != tbPublisher.PublisherId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tbPublisher);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Đã cập nhật nhà xuất bản");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbPublisherExists(tbPublisher.PublisherId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(PublisherIndex));
            }
            return View(tbPublisher);
        }

        private bool TbPublisherExists(int id)
        {
          return _context.TbPublishers.Any(e => e.PublisherId == id);
        }
    }
}

Bookstore/Areas/Admin/Views/AdminPublisher/PublisherCreate.cshtml
@model Bookstore.Entity.TbPublisher

@{
    Layout = null;
}

<h3 class="text-primary">Thêm nhà xuất bản</h3>
<hr />
<form asp-controller="AdminPublisher" asp-action="PublisherCreate" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-6 form-group">
            <label class="control-label fw-bold">Tên nhà xuất bản</label>
            <br />
            <input asp-for="PublisherName" class="form-control" />
            <span asp-validation-for="PublisherName" class="text-danger"></span>
        </div>
        <div class="form-group col-6 d-flex align-items-center">
            <div class="switch m-r-10">
                <input asp-for="Status" type="checkbox" id="switch-1" checked="">
                <label for="switch-1"></label>
            </div>
            <label>Trạng thái</label>
        </div>
    </div>
    <br />
    <div class="form-group">
        <input type="submit" value="Thêm" class="btn btn-primary" />
    </div>
</form>

Bookstore/Areas/Admin/Views/AdminPublisher/PublisherEdit.cshtml
@model Bookstore.Entity.TbPublisher

@{
    Layout = null;
}

<h3 class="text-warning">Cập nhật nhà xuất bản</h3>
<hr />
<form asp-action="PublisherEdit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="PublisherId" />
    <div class="row">
        <div class="col-6 form-group">
            <label class="control-label fw-bold">Tên thể loại</label>
            <br />
            <input asp-for="PublisherName" class="form-control" />
            <span asp-validation-for="PublisherName" class="text-danger"></span>
        </div>
        <div class="form-group col-6 d-flex align-items-center">
            <div class="switch m-r-10">
                <input asp-for="Status" type="checkbox" id="switch-1">
                <label for="switch-1"></label>
            </div>
            <label>Trạng thái</label>
        </div>
    </div>
    <br />
    <div class="form-group">
        <input type="submit" value="Lưu" class="btn btn-warning m-r-5" />
    </div>
</form>

Bookstore/Areas/Admin/Views/AdminPublisher/PublisherIndex.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<Bookstore.Entity.TbPublisher>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    var number = 1;
}

<div id="modal" class="modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button id="Close" type="button" class="close btn btn-danger btn-tone m-r-5" data-dismiss="modal">
                    <i class="anticon anticon-close"></i>
                </button>
            </div>
            <div class="modal-body" id="sub-modal">
            </div>
        </div>
    </div>
</div>

<div class="">
    <div class="page-header">
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h4>Quản lý nhà xuất bản</h4>
            <button id="Create" class="btn btn-primary m-r-5">Thêm nhà xuất bản</button>
            <hr />
            <div class="m-t-25">
                <table id="data-table" class="table ">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Tên nhà xuất bản</th>
                            <th>Trạng thái</th>
                            <th>Cập nhật</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @number
                                        @{
                                            number++;
                                        }
                                    </td>
                                    <td>@item.PublisherName</td>
                                    <td class="">
                                        @if (item.Status == true)
                                        {
                                            <span class="badge badge-pill badge-success">True</span>
                                        }
                                        else
                                        {
                                            <span class="badge badge-pill badge-danger">False</span>
                                        }
                                    </td>
                                    <td>
                                        <button class="btn btn-warning btn-tone m-r-5 edit" value="@item.PublisherId"><i class='bx bx-edit-alt'></i></button>
                                        @*<button class="btn btn-danger btn-tone m-r-5 delete" value="@item.TypeId"><i class='bx bx-trash-alt'></i></button>*@
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
                <div aria-label="Page navigation example">
                    <ul class="pagination">
                        <pager class="pagination" list="@Model" options="@PagedListRenderOptions.Bootstrap4PageNumbersPlusFirstAndLast" asp-area="Admin" asp-controller="AdminPublisher" asp-action="PublisherIndex" />
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {

            $('#Close').click(function () {
                $("#modal").removeClass('d-block');
            });

            $('#Create').click(function () {
                $("#modal").addClass('d-block');
                let str = "/Admin/AdminPublisher/PublisherCreate/";
                $("#sub-modal").load(str);
            });

            $('.edit').each(function (index, value) {
                $(value).click(function () {
                    $('#modal').addClass('d-block');
                    let str = "/Admin/AdminPublisher/PublisherEdit/" + $(value).val();
                    console.log($(value).val());
                    $('#sub-modal').load(str);
                });
            });
        });
    </script>
}