Bookstore/Areas/Admin/Controllers/AdminCustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bookstore.Entity;
using AspNetCoreHero.ToastNotification.Abstractions;
using PagedList.Core;

namespace Bookstore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminCustomerController : Controller
    {
        private readonly dbBookstoreContext _context;
        public INotyfService _notyfService { get; }

        public AdminCustomerController(dbBookstoreContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        public IActionResult CustomerIndex(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 10;
            var lsCustomer = _context.TbCustomers.AsNoTracking().OrderByDescending(x => x.FullName);

            PagedList<TbCustomer> models = new PagedList<TbCustomer>(lsCustomer, pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        public async Task<IActionResult> CustomerDetails(int? id)
        {
            if (id == null || _context.TbCustomers == null)
            {
                return NotFound();
            }

            var tbCustomer = await _context.TbCustomers
                .Include(t => t.Location)
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (tbCustomer == null)
            {
                return NotFound();
            }

            return View(tbCustomer);
        }

        public async Task<IActionResult> CustomerEdit(int? id)
        {
            if (id == null || _context.TbCustomers == null)
            {
                return NotFound();
            }

            var tbCustomer = await _context.TbCustomers.FindAsync(id);
            if (tbCustomer == null)
            {
                return NotFound();
            }
            ViewData["LocationId"] = new SelectList(_context.TbLocations, "LocationId", "LocationId", tbCustomer.LocationId);
            return View(tbCustomer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CustomerEdit(int id, [Bind("CustomerId,FullName,BirthDate,Address,Email,Phone,LocationId,District,Ward,CreateDate,Password,Salt,Active")] TbCustomer tbCustomer)
        {
            if (id != tbCustomer.CustomerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tbCustomer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbCustomerExists(tbCustomer.CustomerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocationId"] = new SelectList(_context.TbLocations, "LocationId", "LocationId", tbCustomer.LocationId);
            return View(tbCustomer);
        }


        private bool TbCustomerExists(int id)
        {
          return (_context.TbCustomers?.Any(e => e.CustomerId == id)).GetValueOrDefault();
        }
    }
}

Bookstore/Areas/Admin/Views/AdminCustomer/CustomerCreate.cshtml
@model Bookstore.Entity.TbCustomer

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>TbCustomer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <select asp-for="LocationId" class ="form-control" asp-items="ViewBag.LocationId"></select>
            </div>
            <div class="form-group">
                <label asp-for="District" class="control-label"></label>
                <input asp-for="District" class="form-control" />
                <span asp-validation-for="District" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ward" class="control-label"></label>
                <input asp-for="Ward" class="form-control" />
                <span asp-validation-for="Ward" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salt" class="control-label"></label>
                <input asp-for="Salt" class="form-control" />
                <span asp-validation-for="Salt" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Bookstore/Areas/Admin/Views/AdminCustomer/CustomerDetails.cshtml
@model Bookstore.Entity.TbCustomer

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>TbCustomer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.District)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.District)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ward)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ward)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location.LocationId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CustomerId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Bookstore/Areas/Admin/Views/AdminCustomer/CustomerEdit.cshtml
@model Bookstore.Entity.TbCustomer

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>TbCustomer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CustomerId" />
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <select asp-for="LocationId" class="form-control" asp-items="ViewBag.LocationId"></select>
                <span asp-validation-for="LocationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="District" class="control-label"></label>
                <input asp-for="District" class="form-control" />
                <span asp-validation-for="District" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ward" class="control-label"></label>
                <input asp-for="Ward" class="form-control" />
                <span asp-validation-for="Ward" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salt" class="control-label"></label>
                <input asp-for="Salt" class="form-control" />
                <span asp-validation-for="Salt" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Bookstore/Areas/Admin/Views/AdminCustomer/CustomerIndex.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<Bookstore.Entity.TbCustomer>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    var number = 1;
}


<div id="modal" class="modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button id="Close" type="button" class="close btn btn-danger btn-tone m-r-5" data-dismiss="modal">
                    <i class="anticon anticon-close"></i>
                </button>
            </div>
            <div class="modal-body" id="sub-modal">
            </div>
        </div>
    </div>
</div>

<div class="">
    <div class="page-header">
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h4>Quản lý tài khoản</h4>
            <hr />
            <div class="input-group rounded" style="width:300px">
                        <input id="keyword" name="keyword" type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
                        <span class="input-group-text border-0" id="search-addon">
                            <i class='bx bx-search'></i>
                        </span>
                    </div>
            <div class="m-t-25">
                <table id="data-table" class="table ">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Tên khách hàng</th>
                            <th>Thông tin liên lạc</th>
                            <th>Ngày tạo tài khoản</th>
                            <th>Trạng thái</th>
                        </tr>
                    </thead>
                    <tbody id="records_table">
                        @if (Model != null)
                        {
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @number
                                        @{
                                            number++;
                                        }
                                    </td>
                                    <td>@item.FullName</td>
                                    <td>
                                        <p>@item.Phone</p>
                                        <p>@item.Email</p>
                                        <p>@item.Address</p>
                                    </td>
                                    <td>@item.CreateDate</td>
                                    <td class="">
                                        @if (item.Active == true)
                                        {
                                            <span class="badge badge-pill badge-success">True</span>
                                        }
                                        else
                                        {
                                            <span class="badge badge-pill badge-danger">False</span>
                                        }
                                    </td>
                                    <td>
                                        @*<button class="btn btn-warning btn-tone m-r-5 edit" value="@item.CustomerId"><i class='bx bx-edit-alt'></i></button>*@
                                        @*<button class="btn btn-danger btn-tone m-r-5 delete" value="@item.TypeId"><i class='bx bx-trash-alt'></i></button>*@
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
                <div aria-label="Page navigation example">
                    <ul class="pagination">
                        <pager class="pagination" list="@Model" options="@PagedListRenderOptions.Bootstrap4PageNumbersPlusFirstAndLast" asp-area="Admin" asp-controller="AdminCustomer" asp-action="CustomerIndex" />
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {

            $('#Close').click(function () {
                $("#modal").removeClass('d-block');
            });

            $('#Create').click(function () {
                $("#modal").addClass('d-block');
                let str = "/Admin/AdminCustomer/CustomerCreate/";
                $("#sub-modal").load(str);
            });

            $('.edit').each(function (index, value) {
                $(value).click(function () {
                    $('#modal').addClass('d-block');
                    let str = "/Admin/AdminCustomer/CustomerEdit/" + $(value).val();
                    console.log($(value).val());
                    $('#sub-modal').load(str);
                });
            });

            $("#keyword").keyup(function () {
                var strkeyword = $('#keyword').val();
                $.ajax({
                    url: '/Admin/Search/FindCustomer/',
                    datatype: "json",
                    type: "POST",
                    data: { keyword: strkeyword },
                    async: true,
                    success: function (results) {
                        $("#records_table").html("");
                        $("#records_table").html(results);
                    },
                    error: function (xhr) {
                        alert('error');
                    }
                });
            });

        });
    </script>
}