Bookstore/Areas/Admin/Controllers/AdminBookTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bookstore.Entity;
using AspNetCoreHero.ToastNotification.Abstractions;
using AspNetCoreHero.ToastNotification.Notyf;
using PagedList.Core;

namespace Bookstore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminBookTypeController : Controller
    {
        private readonly dbBookstoreContext _context;
        public INotyfService _notyfService { get; }

        public AdminBookTypeController(dbBookstoreContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        public IActionResult BookTypeIndex(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 8;
            var lsBookType = _context.TbBookTypes.AsNoTracking().OrderByDescending(x => x.TypeName);

            PagedList<TbBookType> models = new PagedList<TbBookType>(lsBookType, pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        public IActionResult BookTypeCreate()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BookTypeCreate([Bind("TypeId,TypeName,Status,Sort,Thumb,ParentId")] TbBookType tbBookType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tbBookType);
                await _context.SaveChangesAsync();
                _notyfService.Success("Đã thêm thể loại sách");
                return RedirectToAction(nameof(BookTypeIndex));
            }
            return View(tbBookType);
        }

        public async Task<IActionResult> BookTypeEdit(int? id)
        {
            if (id == null || _context.TbBookTypes == null)
            {
                return NotFound();
            }

            var tbBookType = await _context.TbBookTypes.FindAsync(id);
            if (tbBookType == null)
            {
                return NotFound();
            }
            return View(tbBookType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BookTypeEdit(int id, [Bind("TypeId,TypeName,Status,Sort,Thumb,ParentId")] TbBookType tbBookType)
        {
            if (id != tbBookType.TypeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tbBookType);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Đã cập nhật thể loại sách");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbBookTypeExists(tbBookType.TypeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(BookTypeIndex));
            }
            return View(tbBookType);
        }

        public async Task<IActionResult> BookTypeDelete(int? id)
        {
            if (id == null || _context.TbBookTypes == null)
            {
                return NotFound();
            }

            var tbBookType = await _context.TbBookTypes
                .FirstOrDefaultAsync(m => m.TypeId == id);
            if (tbBookType == null)
            {
                return NotFound();
            }

            return View(tbBookType);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BookTypeDeleteConfirmed(int id)
        {
            if (_context.TbBookTypes == null)
            {
                return Problem("Entity set 'dbBookstoreContext.TbBookTypes'  is null.");
            }
            var tbBookType = await _context.TbBookTypes.FindAsync(id);
            if (tbBookType != null)
            {
                _context.TbBookTypes.Remove(tbBookType);
            }
            
            await _context.SaveChangesAsync();
            _notyfService.Error("Đã xóa thể loại sách");
            return RedirectToAction(nameof(BookTypeIndex));
        }

        private bool TbBookTypeExists(int id)
        {
          return _context.TbBookTypes.Any(e => e.TypeId == id);
        }
    }
}

Bookstore/Areas/Admin/Controllers/AdminHomeController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Bookstore.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bookstore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminHomeController : Controller
    {
        private readonly dbBookstoreContext _context;
        public INotyfService _notyfService { get; }

        public AdminHomeController(dbBookstoreContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        [Route("/Admin")]
        public IActionResult Admin()
        {
            int gia1 = 0;

            DateTime StartDate = DateTime.Today.AddDays(-30);
            DateTime EndDate1 = DateTime.Now;

            var hoadonban = _context.TbOrders.Where(s => s.OrderDate >= StartDate && s.OrderDate <= EndDate1).ToList();
            foreach (var element in hoadonban)
            {
                var dondat = _context.TbOrderDetails.Where(s => s.OrderId == element.OrderId).ToList();
                foreach (var element2 in dondat)
                {
                    if (element2.PromotionPrice == null)
                    {
                        int strSanPham = (int)(Convert.ToInt32(element2.Price) * element2.Amount);
                        gia1 += strSanPham;
                    }
                    else
                    {
                        int strSanPham = (int)(Convert.ToInt32(element2.PromotionPrice) * element2.Amount);
                        gia1 += strSanPham;
                    }
                }
            }
            ViewBag.gialai = gia1;

            ViewBag.CountBook = _context.TbBooks.ToList().Count();
            ViewBag.CountOrder = _context.TbOrders.ToList().Count();
            ViewBag.CountCustomer = _context.TbCustomers.ToList().Count();


            ViewBag.loai1 = _context.TbBooks.Where(s => s.TypeId == 1).Count();
            ViewBag.loai2 = _context.TbBooks.Where(s => s.TypeId == 3).Count();
            ViewBag.loai3 = _context.TbBooks.Where(s => s.TypeId == 4).Count();
            ViewBag.loai4 = _context.TbBooks.Where(s => s.TypeId == 5).Count();
            ViewBag.loai5 = _context.TbBooks.Where(s => s.TypeId == 6).Count();
            ViewBag.loai6 = _context.TbBooks.Where(s => s.TypeId == 7).Count();
            ViewBag.loai7 = _context.TbBooks.Where(s => s.TypeId == 1008).Count();
            ViewBag.loai8 = _context.TbBooks.Where(s => s.TypeId == 1009).Count();
            ViewBag.loai9 = _context.TbBooks.Where(s => s.TypeId == 1010).Count();

            return View();
        }
    }
}

Bookstore/Areas/Admin/Controllers/AdminPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bookstore.Entity;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PagedList.Core;
using Bookstore.Helpper;

namespace Bookstore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminPostsController : Controller
    {
		private readonly dbBookstoreContext _context;
		public INotyfService _notyfService { get; }

		public AdminPostsController(dbBookstoreContext context, INotyfService notyfService)
		{
			_context = context;
			_notyfService = notyfService;
        }
        public IActionResult PostIndex(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 8;
			var lsPost = _context.TbPosts.AsNoTracking().OrderByDescending(x => x.PostId);

			PagedList<TbPost> models = new PagedList<TbPost>(lsPost, pageNumber, pageSize);

			ViewBag.CurrentPage = pageNumber;
			return View(models);
		}

        public async Task<IActionResult> PostDetails(int? id)
        {
            if (id == null || _context.TbPosts == null)
            {
                return NotFound();
            }

            var tbPost = await _context.TbPosts
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (tbPost == null)
            {
                return NotFound();
            }

            return View(tbPost);
        }

        public IActionResult PostCreate()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostCreate([Bind("PostId,Title,Scontents,Contents,Thumb,Status,CreatedDate,Tags,IsHot,IsNewfeed,Views,Active")] TbPost tbPost, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                tbPost.Title = Utilities.ToTitleCase(tbPost.Title);
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string image = Utilities.SEOUrl(tbPost.Title) + extension;
                    tbPost.Thumb = await Utilities.UploadFile(fThumb, @"post", image.ToLower());
                }
                if (string.IsNullOrEmpty(tbPost.Thumb)) tbPost.Thumb = "default-book.jpg";

                tbPost.CreatedDate = DateTime.Now;
                _context.Add(tbPost);
                await _context.SaveChangesAsync();
                _notyfService.Success("Thêm tin tức thành công");
                return RedirectToAction(nameof(PostIndex));
            }
            return View(tbPost);
        }

        public async Task<IActionResult> PostEdit(int? id)
        {
            if (id == null || _context.TbPosts == null)
            {
                return NotFound();
            }

            var tbPost = await _context.TbPosts.FindAsync(id);
            if (tbPost == null)
            {
                return NotFound();
            }
            return View(tbPost);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostEdit(int id, [Bind("PostId,Title,Scontents,Contents,Thumb,Status,CreatedDate,Tags,IsHot,IsNewfeed,Views,Active")] TbPost tbPost, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != tbPost.PostId)
            {
                return NotFound();
            }

            try
            {
                tbPost.Title = Utilities.ToTitleCase(tbPost.Title);
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string image = Utilities.SEOUrl(tbPost.Title) + extension;
                    tbPost.Thumb = await Utilities.UploadFile(fThumb, @"post", image.ToLower());
                }
                if (string.IsNullOrEmpty(tbPost.Thumb)) tbPost.Thumb = "default-book.jpg";

                tbPost.CreatedDate = DateTime.Now;
                _context.Update(tbPost);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TbPostExists(tbPost.PostId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(PostIndex));
        }

        public async Task<IActionResult> PostDelete(int? id)
        {
            if (id == null || _context.TbPosts == null)
            {
                return NotFound();
            }

            var tbPost = await _context.TbPosts
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (tbPost == null)
            {
                return NotFound();
            }

            return View(tbPost);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TbPosts == null)
            {
                return Problem("Entity set 'dbBookstoreContext.TbPosts'  is null.");
            }
            var tbPost = await _context.TbPosts.FindAsync(id);
            if (tbPost != null)
            {
                _context.TbPosts.Remove(tbPost);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TbPostExists(int id)
        {
          return (_context.TbPosts?.Any(e => e.PostId == id)).GetValueOrDefault();
        }
    }
}

Bookstore/Areas/Admin/Views/AdminPosts/PostCreate.cshtml
@model Bookstore.Entity.TbPost

@{
    ViewData["Title"] = "Thêm tin tức";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="AdminHome" asp-action="Admin" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <span class="breadcrumb-item active"></span>
        </nav>
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="AdminPosts" asp-action="PostIndex" class="breadcrumb-item">Tin tức</a>
        </nav>
    </div>
</div>

<form asp-controller="AdminPosts" asp-action="PostCreate" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-right justify-content-between">
            <div class="media align-items-center m-b-15">
                
            </div>
            <div class="m-b-15">
                <button type="submit" class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Lưu</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN TIN TỨC</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tiêu đề</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>


                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Ảnh</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>Nội dung</label>
                        <textarea class="form-control" rows="15" cols="100" asp-for="Contents"></textarea>
                        <span asp-validation-for="Contents" class="text-danger"></span>
                    </div>
                    </div>
                    <div class="form-group d-flex align-items-center">
                        <div class="switch m-r-10">
                            <input asp-for="Status" type="checkbox" id="switch-1" checked="">
                            <label for="switch-1"></label>
                        </div>
                        <label>Trạng thái</label>
                    </div>
                    <div class="form-group d-flex align-items-center">
                        <div class="switch m-r-10">
                            <input asp-for="IsNewfeed" type="checkbox" id="switch-2">
                            <label for="switch-2"></label>
                        </div>
                        <label>Hiện ở trang chủ</label>
                    </div>
                </div>
            </div>
        </div>
</form>

Bookstore/Areas/Admin/Views/AdminPosts/PostDetails.cshtml
@model Bookstore.Entity.TbPost

@{
    ViewData["Title"] = "Chi tiết tin tức";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="m-b-15">
            <a asp-controller="AdminPosts" asp-action="PostIndex" class="btn btn-danger">
                <i class="anticon anticon-edit"></i>
                <span>Trở về</span>
            </a>
        </div>
        <div class="m-b-15">
            <a asp-controller="AdminPosts" asp-action="PostEdit" asp-route-id="@Model.PostId" class="btn btn-primary">
                <i class="anticon anticon-edit"></i>
                <span>Cập nhật</span>
            </a>
        </div>
    </div>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#product-overview">Chi tiết tin</a>
        </li>
        @*        <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#product-images">Product Images</a>
        </li>*@
    </ul>
</div>
<div class="container-fluid">
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-overview">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="product-info-table m-t-20">
                            <tbody>
                                <tr>
                                    <td>ID:</td>
                                    <td class="text-dark font-weight-semibold">@Model.PostId</td>
                                </tr>
                                <tr>
                                    <td>Tên sách:</td>
                                    <td>@Model.Title</td>
                                </tr>
                                <tr>
                                    <td>Năm phát hành:</td>
                                    <td>@Model.CreatedDate</td>
                                </tr>
                                <tr>
                                    <td>Hình ảnh:</td>
                                    <td><img width="120px" src="~/images/post/@Model.Thumb" alt="@Model.Title" /></td>
                                </tr>
                                <tr>
                                    <td>Trạng thái:</td>
                                    <td>
                                        @if (Model.Status == true)
                                        {
                                            <div class="d-flex align-items-center">
                                                <div class="badge rounded-pill bg-success">True</div>
                                            </div>
                                        }
                                        else
                                        {
                                            <div class="d-flex align-items-center">
                                                <div class="badge rounded-pill bg-danger">Fail</div>
                                            </div>
                                        }
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="product-info-table m-t-20">
                            <tbody>
                                <tr>
                                    <td>IsHot:</td>
                                    <td>
                                        @if (Model.IsNewfeed == true)
                                        {
                                            <div class="d-flex align-items-center">
                                                <div class="badge rounded-pill bg-success">Tin hot</div>
                                            </div>
                                        }
                                        else
                                        {
                                            <div class="d-flex align-items-center">
                                                <div class="badge rounded-pill bg-danger"></div>
                                            </div>
                                        }
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Nội dung</h4>
                </div>
                <div class="card-body">
                    <p>@Model.Contents</p>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-images">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <img class="img-fluid" src="assets/images/others/product-1.jpg" alt="">
                        </div>
                        <div class="col-md-3">
                            <img class="img-fluid" src="assets/images/others/product-2.jpg" alt="">
                        </div>
                        <div class="col-md-3">
                            <img class="img-fluid" src="assets/images/others/product-3.jpg" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Bookstore/Areas/Admin/Views/AdminPosts/PostEdit.cshtml
@model Bookstore.Entity.TbPost

@{
    ViewData["Title"] = "Cập nhật tin tức";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a asp-area="Admin" asp-controller="AdminHome" asp-action="Admin" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
			<span class="breadcrumb-item active"></span>
		</nav>
		<nav class="breadcrumb breadcrumb-dash">
			<a asp-area="Admin" asp-controller="AdminPosts" asp-action="PostIndex" class="breadcrumb-item">Tin tức</a>
		</nav>
	</div>
</div>
<form asp-controller="AdminPosts" asp-action="PostEdit" asp-route-id="@Model.PostId" method="post" enctype="multipart/form-data">
	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
	<input type="hidden" asp-for="PostId" />
	<input type="hidden" asp-for="Thumb" />
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-right justify-content-between">
            <div class="media align-items-center m-b-15">
            </div>
            <div class="m-b-15">
                <button type="submit" class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Lưu</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN TIN TỨC</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tiêu đề</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>


                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Ảnh</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>Nội dung</label>
                        <textarea class="form-control" rows="15" cols="100" asp-for="Contents"></textarea>
                        <span asp-validation-for="Contents" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group d-flex align-items-center">
                    <div class="switch m-r-10">
                        <input asp-for="Status" type="checkbox" id="switch-1" >
                        <label for="switch-1"></label>
                    </div>
                    <label>Trạng thái</label>
                </div>
                <div class="form-group d-flex align-items-center">
                    <div class="switch m-r-10">
                        <input asp-for="IsNewfeed" type="checkbox" id="switch-2">
                        <label for="switch-2"></label>
                    </div>
                    <label>Hiện ở trang chủ</label>
                </div>
            </div>
        </div>
    </div>
</form>

Bookstore/Areas/Admin/Views/AdminPosts/PostIndex.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<Bookstore.Entity.TbPost>

@{
    ViewData["Title"] = "Quản lý tin tức";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    var number = 1;
}

<div class="">
    <div class="page-header">
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a asp-area="Admin" asp-controller="AdminHome" asp-action="Admin"> <i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            </nav>
        </div>>
    </div>
    <div class="card">
        <div class="card-body">
            <h4>Quản lý tin tức</h4>
            <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminPosts" asp-action="PostCreate">
                <i class="anticon anticon-plus-circle m-r-5"></i>
                <span>Thêm tin</span>
            </a>
            <hr />
            <div class="m-t-25">
                <table id="data-table" class="table ">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Tiêu đề</th>
                            <th>Ngày tạo</th>
                            <th>Ảnh</th>
                            <th>Trạng thái</th>
                            <th>Cập nhật</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @number
                                        @{
                                            number++;
                                        }
                                    </td>
                                    <td>@item.Title</td>
                                    <td>@item.CreatedDate</td>
                                    <td><img width="120px" src="~/images/post/@item.Thumb" alt="@item.Thumb" /></td>
                                    <td class="">
                                        @if (item.Status == true)
                                        {
                                            <span class="badge badge-pill badge-success">True</span>
                                        }
                                        else
                                        {
                                            <span class="badge badge-pill badge-danger">False</span>
                                        }
                                    </td>
                                    <td>
                                        <a asp-controller="AdminPosts" asp-action="PostDetails" asp-route-id="@item.PostId" class="btn btn-outline-primary"><i class='bx bx-detail'></i></a>
                                        <a asp-controller="AdminPosts" asp-action="PostEdit" asp-route-id="@item.PostId" class="btn btn-outline-warning"><i class='bx bx-edit-alt'></i></a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
                <div aria-label="Page navigation example">
                    <ul class="pagination">
                        <pager class="pagination" list="@Model" options="@PagedListRenderOptions.Bootstrap4PageNumbersPlusFirstAndLast" asp-area="Admin" asp-controller="AdminBookType" asp-action="BookTypeIndex" />
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {

            $('#Close').click(function () {
                $("#modal").removeClass('d-block');
            });

            $('#Create').click(function () {
                $("#modal").addClass('d-block');
                let str = "/Admin/AdminPosts/PostCreate/";
                $("#sub-modal").load(str);
            });

            $('.edit').each(function (index, value) {
                $(value).click(function () {
                    $('#modal').addClass('d-block');
                    let str = "/Admin/AdminPosts/PostEdit/" + $(value).val();
                    console.log($(value).val());
                    $('#sub-modal').load(str);
                });
            });

            $('.delete').each(function (index, value) {
                $(value).click(function () {
                    $('#modal').addClass('d-block');
                    let str = "/Admin/AdminPosts/PostDelete/" + $(value).val();
                    console.log($(value).val());
                    $('#sub-modal').load(str);
                });
            });
        });
    </script>
}